### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [teekamsuthar/Mutify#1]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by teekamsuthar** [comment]
Hi there! 
Actually, I am planning to do this from the very beginning. And I've been collecting the crash reports from the Play Store version of Mutify since. There are a few bugs that is causing the app to crash on some devices. So, I just want to make sure it's a stable update before pushing it to F-Droid or any other marketplace. I'm definitely going to do it this time along, as well as the latest commit to this repo very soon. 
You're also welcome to contribute to the app source if you will :)
Thanks!

**Comment by mdhossain026** [comment]
Hi,
Would you discuss about bugs which are causing the app crashing. I am interested to contribute the app to fix the bug.

Thanks,
